ALTER TABLE players ADD COLUMN IF NOT EXISTS spirit_root_id VARCHAR(80);
ALTER TABLE players ADD COLUMN IF NOT EXISTS realm_stage SMALLINT NOT NULL DEFAULT 1;

UPDATE players
SET spirit_root_id = CASE spiritual_root
    WHEN 'Thien Linh Can' THEN 'THIEN_LINH_CAN'
    WHEN 'Bang Linh Can' THEN 'BANG_LINH_CAN'
    WHEN 'Loi Linh Can' THEN 'LOI_LINH_CAN'
    WHEN 'Phong Linh Can' THEN 'PHONG_LINH_CAN'
    WHEN 'Kim Linh Can' THEN 'KIM_LINH_CAN'
    WHEN 'Moc Linh Can' THEN 'MOC_LINH_CAN'
    WHEN 'Thuy Linh Can' THEN 'THUY_LINH_CAN'
    WHEN 'Hoa Linh Can' THEN 'HOA_LINH_CAN'
    WHEN 'Tho Linh Can' THEN 'THO_LINH_CAN'
    WHEN 'Tap Can' THEN 'TAP_CAN'
    WHEN 'Tạp Căn' THEN 'TAP_CAN'
    ELSE spirit_root_id
END
WHERE spirit_root_id IS NULL;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'players_realm_stage_positive'
    ) THEN
        ALTER TABLE players
        ADD CONSTRAINT players_realm_stage_positive CHECK (realm_stage > 0) NOT VALID;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS idempotency_records (
    operation_id TEXT PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    operation_type VARCHAR(80) NOT NULL,
    request_hash TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    response JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    CONSTRAINT idempotency_status_valid CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED_RETRYABLE'))
);

CREATE INDEX IF NOT EXISTS idempotency_records_player_created_idx
ON idempotency_records (player_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idempotency_records_expires_idx
ON idempotency_records (expires_at)
WHERE expires_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id TEXT NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS outbox_events_pending_idx
ON outbox_events (occurred_at, id)
WHERE processed_at IS NULL;
