CREATE TABLE IF NOT EXISTS inventory_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    item_id VARCHAR(80) NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    rarity VARCHAR(30),
    instance_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    legacy_item_id BIGINT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS inventory_stacks_player_item_idx
ON inventory_stacks (player_id, item_id);

CREATE TABLE IF NOT EXISTS equipment_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    template_id VARCHAR(80) NOT NULL,
    rarity VARCHAR(30),
    instance_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    equipped_slot VARCHAR(30),
    legacy_item_id BIGINT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS equipment_instances_player_template_idx
ON equipment_instances (player_id, template_id);

CREATE UNIQUE INDEX IF NOT EXISTS equipment_instances_player_slot_unique
ON equipment_instances (player_id, equipped_slot)
WHERE equipped_slot IS NOT NULL;
