ALTER TABLE player_shop_purchases
ALTER COLUMN price TYPE NUMERIC(30, 0)
USING price::NUMERIC(30, 0);

ALTER TABLE player_shop_purchases
ALTER COLUMN quantity TYPE BIGINT
USING quantity::BIGINT;

ALTER TABLE player_craft_logs
ALTER COLUMN currency_cost TYPE NUMERIC(30, 0)
USING currency_cost::NUMERIC(30, 0);

ALTER TABLE player_craft_logs
ALTER COLUMN quantity TYPE BIGINT
USING quantity::BIGINT;

CREATE TABLE IF NOT EXISTS resource_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    resource_type VARCHAR(40) NOT NULL,
    resource_id VARCHAR(80) NOT NULL,
    delta NUMERIC(30, 0) NOT NULL,
    balance_after NUMERIC(30, 0) NOT NULL,
    reason VARCHAR(80) NOT NULL,
    reference_type VARCHAR(80) NOT NULL,
    reference_id TEXT NOT NULL,
    operation_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT resource_ledger_balance_non_negative CHECK (balance_after >= 0),
    CONSTRAINT resource_ledger_resource_id_not_blank CHECK (length(trim(resource_id)) > 0),
    CONSTRAINT resource_ledger_reference_id_not_blank CHECK (length(trim(reference_id)) > 0)
);

CREATE INDEX IF NOT EXISTS resource_ledger_player_created_idx
ON resource_ledger (player_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS resource_ledger_operation_idx
ON resource_ledger (operation_id)
WHERE operation_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS resource_ledger_reference_idx
ON resource_ledger (reference_type, reference_id);

CREATE TABLE IF NOT EXISTS player_period_counters (
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    counter_type VARCHAR(80) NOT NULL,
    subject_id VARCHAR(160) NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    period_key VARCHAR(20) NOT NULL,
    value BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, counter_type, subject_id, period_type, period_key),
    CONSTRAINT player_period_counters_value_non_negative CHECK (value >= 0),
    CONSTRAINT player_period_counters_period_type_valid
        CHECK (period_type IN ('DAILY', 'WEEKLY', 'MONTHLY', 'LIFETIME'))
);

CREATE INDEX IF NOT EXISTS player_period_counters_subject_idx
ON player_period_counters (counter_type, subject_id, period_type, period_key);

ALTER TABLE player_shop_purchases
ADD COLUMN IF NOT EXISTS operation_id TEXT;

ALTER TABLE player_craft_logs
ADD COLUMN IF NOT EXISTS operation_id TEXT;

ALTER TABLE player_exchange_logs
ADD COLUMN IF NOT EXISTS operation_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS player_shop_purchases_operation_unique
ON player_shop_purchases (operation_id)
WHERE operation_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS player_craft_logs_operation_unique
ON player_craft_logs (operation_id)
WHERE operation_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS player_exchange_logs_operation_unique
ON player_exchange_logs (operation_id)
WHERE operation_id IS NOT NULL;
