CREATE TABLE IF NOT EXISTS reward_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    claim_type VARCHAR(80) NOT NULL,
    source_ref TEXT NOT NULL,
    operation_id TEXT NOT NULL,
    reward_table_id VARCHAR(80),
    rolled_reward_snapshot JSONB NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reward_claims_claim_type_not_blank CHECK (length(trim(claim_type)) > 0),
    CONSTRAINT reward_claims_source_ref_not_blank CHECK (length(trim(source_ref)) > 0),
    CONSTRAINT reward_claims_operation_id_not_blank CHECK (length(trim(operation_id)) > 0),
    CONSTRAINT reward_claims_operation_unique UNIQUE (operation_id),
    CONSTRAINT reward_claims_business_unique UNIQUE (player_id, claim_type, source_ref)
);

CREATE INDEX IF NOT EXISTS reward_claims_player_claimed_idx
ON reward_claims (player_id, claimed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS reward_claims_source_idx
ON reward_claims (claim_type, source_ref);
