CREATE TABLE IF NOT EXISTS activity_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    activity_type VARCHAR(80) NOT NULL,
    content_id VARCHAR(160) NOT NULL,
    operation_id TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',
    input_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_snapshot JSONB,
    reward_table_id VARCHAR(80),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT activity_runs_operation_unique UNIQUE (operation_id),
    CONSTRAINT activity_runs_status_valid CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
    CONSTRAINT activity_runs_activity_type_not_blank CHECK (length(trim(activity_type)) > 0),
    CONSTRAINT activity_runs_content_id_not_blank CHECK (length(trim(content_id)) > 0)
);

CREATE INDEX IF NOT EXISTS activity_runs_player_started_idx
ON activity_runs (player_id, started_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS activity_runs_content_idx
ON activity_runs (activity_type, content_id, started_at DESC);

ALTER TABLE reward_claims
ADD COLUMN IF NOT EXISTS activity_run_id BIGINT REFERENCES activity_runs(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS reward_claims_activity_run_unique
ON reward_claims (activity_run_id)
WHERE activity_run_id IS NOT NULL;
