ALTER TABLE players
    ADD COLUMN IF NOT EXISTS rebirth_count NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rebirth_policy_revision INT NOT NULL DEFAULT 1;

ALTER TABLE players
    DROP CONSTRAINT IF EXISTS players_rebirth_count_non_negative_integer;

ALTER TABLE players
    ADD CONSTRAINT players_rebirth_count_non_negative_integer
    CHECK (rebirth_count >= 0 AND rebirth_count = TRUNC(rebirth_count));

ALTER TABLE players
    ALTER COLUMN base_atk TYPE NUMERIC USING base_atk::NUMERIC,
    ALTER COLUMN base_def TYPE NUMERIC USING base_def::NUMERIC,
    ALTER COLUMN base_hp TYPE NUMERIC USING base_hp::NUMERIC,
    ALTER COLUMN base_spd TYPE NUMERIC USING base_spd::NUMERIC;

CREATE TABLE IF NOT EXISTS player_rebirth_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    rebirth_number NUMERIC NOT NULL,
    policy_id VARCHAR(80) NOT NULL,
    policy_revision INT NOT NULL,
    operation_id VARCHAR(120) NOT NULL,
    before_snapshot JSONB NOT NULL,
    after_snapshot JSONB NOT NULL,
    reborn_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_rebirth_history_number_positive_integer
        CHECK (rebirth_number > 0 AND rebirth_number = TRUNC(rebirth_number)),
    CONSTRAINT player_rebirth_history_operation_unique UNIQUE (operation_id),
    CONSTRAINT player_rebirth_history_player_number_unique UNIQUE (player_id, rebirth_number)
);

CREATE INDEX IF NOT EXISTS player_rebirth_history_player_time_idx
ON player_rebirth_history (player_id, reborn_at DESC);
