ALTER TABLE players
    ADD COLUMN IF NOT EXISTS spirit_root_quality_tier_id VARCHAR(50);

CREATE TABLE IF NOT EXISTS player_spirit_root_reroll_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    rebirth_number NUMERIC NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumed_at TIMESTAMPTZ,
    consumed_operation_id VARCHAR(120),
    CONSTRAINT spirit_root_entitlement_rebirth_positive_integer
        CHECK (rebirth_number > 0 AND rebirth_number = TRUNC(rebirth_number)),
    CONSTRAINT spirit_root_entitlement_status_valid
        CHECK (status IN ('AVAILABLE', 'CONSUMED')),
    CONSTRAINT spirit_root_entitlement_consumption_consistent
        CHECK (
            (status = 'AVAILABLE' AND consumed_at IS NULL AND consumed_operation_id IS NULL)
            OR
            (status = 'CONSUMED' AND consumed_at IS NOT NULL AND consumed_operation_id IS NOT NULL)
        ),
    CONSTRAINT spirit_root_entitlement_player_rebirth_unique
        UNIQUE (player_id, rebirth_number),
    CONSTRAINT spirit_root_entitlement_consumed_operation_unique
        UNIQUE (consumed_operation_id)
);

CREATE INDEX IF NOT EXISTS spirit_root_entitlement_player_status_idx
ON player_spirit_root_reroll_entitlements (player_id, status, rebirth_number);

CREATE TABLE IF NOT EXISTS player_spirit_root_roll_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    entitlement_id BIGINT NOT NULL UNIQUE
        REFERENCES player_spirit_root_reroll_entitlements(id) ON DELETE RESTRICT,
    operation_id VARCHAR(120) NOT NULL UNIQUE,
    pool_id VARCHAR(80) NOT NULL,
    pool_revision INT NOT NULL,
    previous_spirit_root_id VARCHAR(80),
    previous_quality_tier_id VARCHAR(50),
    new_spirit_root_id VARCHAR(80) NOT NULL,
    new_quality_tier_id VARCHAR(50) NOT NULL,
    roll_snapshot JSONB NOT NULL,
    rolled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS spirit_root_roll_history_player_time_idx
ON player_spirit_root_roll_history (player_id, rolled_at DESC);
