CREATE TABLE IF NOT EXISTS player_map_states (
    player_id VARCHAR(50) PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
    current_map_id VARCHAR(80) NOT NULL,
    movement_version BIGINT NOT NULL DEFAULT 0 CHECK (movement_version >= 0),
    moved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS player_map_states_current_map_idx
ON player_map_states (current_map_id, player_id);

CREATE TABLE IF NOT EXISTS player_map_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    operation_id TEXT NOT NULL UNIQUE,
    from_map_id VARCHAR(80),
    to_map_id VARCHAR(80) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    moved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_map_movements_direction_valid
        CHECK (direction IN ('INITIALIZE', 'HIGHER', 'LOWER', 'DIRECT_ADMIN')),
    CONSTRAINT player_map_movements_changed
        CHECK (from_map_id IS NULL OR from_map_id <> to_map_id)
);

CREATE INDEX IF NOT EXISTS player_map_movements_player_time_idx
ON player_map_movements (player_id, moved_at DESC, id DESC);
