CREATE TABLE IF NOT EXISTS player_professions (
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    profession_id VARCHAR(80) NOT NULL,
    experience NUMERIC(30, 0) NOT NULL DEFAULT 0,
    grade SMALLINT NOT NULL DEFAULT 1,
    data_revision INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, profession_id),
    CONSTRAINT player_professions_experience_non_negative CHECK (experience >= 0),
    CONSTRAINT player_professions_grade_valid CHECK (grade BETWEEN 1 AND 9),
    CONSTRAINT player_professions_revision_positive CHECK (data_revision > 0)
);

CREATE INDEX IF NOT EXISTS player_professions_player_grade_idx
ON player_professions (player_id, grade DESC, profession_id);

CREATE TABLE IF NOT EXISTS player_learned_recipes (
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    recipe_id VARCHAR(120) NOT NULL,
    source_item_id VARCHAR(120),
    source_ref TEXT,
    learned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS profession_craft_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    profession_id VARCHAR(80) NOT NULL,
    recipe_id VARCHAR(120) NOT NULL,
    batch_quantity SMALLINT NOT NULL,
    profession_grade_at_start SMALLINT NOT NULL,
    experience_reward NUMERIC(30, 0) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',
    input_snapshot JSONB NOT NULL,
    output_snapshot JSONB NOT NULL,
    result_snapshot JSONB,
    start_operation_id TEXT NOT NULL,
    claim_operation_id TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ,
    CONSTRAINT profession_craft_jobs_batch_valid CHECK (batch_quantity BETWEEN 1 AND 99),
    CONSTRAINT profession_craft_jobs_grade_valid CHECK (profession_grade_at_start BETWEEN 1 AND 9),
    CONSTRAINT profession_craft_jobs_experience_non_negative CHECK (experience_reward >= 0),
    CONSTRAINT profession_craft_jobs_status_valid CHECK (status IN ('IN_PROGRESS', 'CLAIMED', 'FAILED')),
    CONSTRAINT profession_craft_jobs_ready_after_start CHECK (ready_at >= started_at),
    CONSTRAINT profession_craft_jobs_start_operation_unique UNIQUE (start_operation_id),
    CONSTRAINT profession_craft_jobs_claim_operation_unique UNIQUE (claim_operation_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS profession_craft_jobs_one_active_slot
ON profession_craft_jobs (player_id, profession_id)
WHERE status = 'IN_PROGRESS';

CREATE INDEX IF NOT EXISTS profession_craft_jobs_player_status_idx
ON profession_craft_jobs (player_id, status, started_at DESC);

CREATE INDEX IF NOT EXISTS profession_craft_jobs_ready_idx
ON profession_craft_jobs (ready_at, player_id)
WHERE status = 'IN_PROGRESS';
