CREATE TABLE IF NOT EXISTS player_economy_activity_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    activity_id VARCHAR(80) NOT NULL,
    operation_id TEXT NOT NULL,
    rules_revision VARCHAR(80) NOT NULL,
    period_key VARCHAR(20) NOT NULL,
    map_id VARCHAR(80) NOT NULL,
    reward_amount NUMERIC(30, 0) NOT NULL,
    roll_seed BIGINT,
    outcome_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_economy_activity_runs_operation_unique UNIQUE (operation_id),
    CONSTRAINT player_economy_activity_runs_reward_non_negative CHECK (reward_amount >= 0),
    CONSTRAINT player_economy_activity_runs_activity_not_blank CHECK (length(trim(activity_id)) > 0),
    CONSTRAINT player_economy_activity_runs_revision_not_blank CHECK (length(trim(rules_revision)) > 0)
);

CREATE INDEX IF NOT EXISTS player_economy_activity_runs_latest_idx
ON player_economy_activity_runs (player_id, activity_id, completed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS player_economy_activity_runs_period_idx
ON player_economy_activity_runs (activity_id, period_key, completed_at DESC);

CREATE TABLE IF NOT EXISTS player_minigame_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    game_id VARCHAR(80) NOT NULL,
    rules_revision VARCHAR(80) NOT NULL,
    operation_id TEXT NOT NULL,
    wager NUMERIC(30, 0) NOT NULL,
    payout NUMERIC(30, 0) NOT NULL DEFAULT 0,
    net_delta NUMERIC(30, 0) NOT NULL DEFAULT 0,
    input_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    outcome_snapshot JSONB,
    rng_snapshot JSONB,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    CONSTRAINT player_minigame_rounds_operation_unique UNIQUE (operation_id),
    CONSTRAINT player_minigame_rounds_wager_non_negative CHECK (wager >= 0),
    CONSTRAINT player_minigame_rounds_payout_non_negative CHECK (payout >= 0),
    CONSTRAINT player_minigame_rounds_status_valid CHECK (status IN ('ACTIVE', 'SETTLED', 'EXPIRED')),
    CONSTRAINT player_minigame_rounds_settled_snapshot_required CHECK (
        status <> 'SETTLED'
        OR (settled_at IS NOT NULL AND outcome_snapshot IS NOT NULL AND rng_snapshot IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS player_minigame_rounds_one_active_game
ON player_minigame_rounds (player_id, game_id)
WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS player_minigame_rounds_history_idx
ON player_minigame_rounds (player_id, settled_at DESC NULLS LAST, id DESC);
