CREATE TABLE IF NOT EXISTS words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_word_id INTEGER,
    word TEXT NOT NULL,
    source_id INTEGER,
    lang_code TEXT NOT NULL,
    normalized_word TEXT NOT NULL,
    first_part TEXT NOT NULL,
    second_part TEXT NOT NULL,
    dictionary_revision VARCHAR(80) NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT words_language_normalized_unique UNIQUE (lang_code, normalized_word),
    CONSTRAINT words_source_identity_unique UNIQUE (source_id, source_word_id),
    CONSTRAINT words_not_blank CHECK (
        length(trim(word)) > 0
        AND length(trim(normalized_word)) > 0
        AND length(trim(first_part)) > 0
        AND length(trim(second_part)) > 0
        AND length(trim(lang_code)) > 0
        AND length(trim(dictionary_revision)) > 0
    )
);

CREATE INDEX IF NOT EXISTS words_language_first_part_idx
ON words (lang_code, first_part, id);

CREATE INDEX IF NOT EXISTS words_language_second_part_idx
ON words (lang_code, second_part, id);

CREATE TABLE IF NOT EXISTS word_chain_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id VARCHAR(30) NOT NULL,
    channel_id VARCHAR(30) NOT NULL,
    started_by VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    start_operation_id TEXT NOT NULL UNIQUE,
    end_operation_id TEXT UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    rules_revision VARCHAR(80) NOT NULL,
    dictionary_revision VARCHAR(80) NOT NULL,
    language_code VARCHAR(20) NOT NULL,
    start_word_id BIGINT NOT NULL REFERENCES words(id) ON DELETE RESTRICT,
    current_word_id BIGINT NOT NULL REFERENCES words(id) ON DELETE RESTRICT,
    current_word_snapshot TEXT NOT NULL,
    required_part TEXT NOT NULL,
    last_success_player_id VARCHAR(50) REFERENCES players(id) ON DELETE SET NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    valid_move_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    participant_count INTEGER NOT NULL DEFAULT 0,
    winner_player_id VARCHAR(50) REFERENCES players(id) ON DELETE SET NULL,
    reward_amount NUMERIC(30, 0) NOT NULL DEFAULT 0,
    outcome_snapshot JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    CONSTRAINT word_chain_sessions_status_valid
        CHECK (status IN ('ACTIVE', 'SETTLED', 'CANCELLED')),
    CONSTRAINT word_chain_sessions_counters_valid CHECK (
        attempt_count >= 0
        AND valid_move_count >= 0
        AND failure_count >= 0
        AND participant_count >= 0
        AND valid_move_count <= attempt_count
        AND failure_count <= attempt_count
        AND valid_move_count + failure_count = attempt_count
    ),
    CONSTRAINT word_chain_sessions_reward_non_negative CHECK (reward_amount >= 0),
    CONSTRAINT word_chain_sessions_end_state_valid CHECK (
        (status = 'ACTIVE' AND ended_at IS NULL AND outcome_snapshot IS NULL)
        OR (status IN ('SETTLED', 'CANCELLED') AND ended_at IS NOT NULL AND outcome_snapshot IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS word_chain_sessions_one_active_channel
ON word_chain_sessions (guild_id, channel_id)
WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS word_chain_sessions_channel_history_idx
ON word_chain_sessions (guild_id, channel_id, started_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS word_chain_sessions_winner_idx
ON word_chain_sessions (winner_player_id, ended_at DESC, id DESC)
WHERE winner_player_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS word_chain_moves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES word_chain_sessions(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    operation_id TEXT NOT NULL UNIQUE,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    word_id BIGINT NOT NULL REFERENCES words(id) ON DELETE RESTRICT,
    submitted_text TEXT NOT NULL,
    normalized_word TEXT NOT NULL,
    first_part TEXT NOT NULL,
    second_part TEXT NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    failure_reason VARCHAR(40),
    result_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT word_chain_moves_sequence_unique UNIQUE (session_id, sequence_no),
    CONSTRAINT word_chain_moves_outcome_valid
        CHECK (outcome IN ('VALID', 'QUALIFIED_FAILURE')),
    CONSTRAINT word_chain_moves_failure_consistent CHECK (
        (outcome = 'VALID' AND failure_reason IS NULL)
        OR (outcome = 'QUALIFIED_FAILURE' AND failure_reason IN ('WRONG_LINK', 'WORD_ALREADY_USED'))
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS word_chain_moves_used_valid_word
ON word_chain_moves (session_id, normalized_word)
WHERE outcome = 'VALID';

CREATE INDEX IF NOT EXISTS word_chain_moves_session_time_idx
ON word_chain_moves (session_id, sequence_no, id);

CREATE INDEX IF NOT EXISTS word_chain_moves_session_player_idx
ON word_chain_moves (session_id, player_id);
