CREATE TABLE IF NOT EXISTS spirit_stone_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id TEXT NOT NULL UNIQUE,
    sender_player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    recipient_player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    gross_amount NUMERIC(30, 0) NOT NULL,
    fee_amount NUMERIC(30, 0) NOT NULL DEFAULT 0,
    received_amount NUMERIC(30, 0) NOT NULL,
    policy_revision VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT spirit_stone_transfers_distinct_players CHECK (sender_player_id <> recipient_player_id),
    CONSTRAINT spirit_stone_transfers_gross_positive CHECK (gross_amount > 0),
    CONSTRAINT spirit_stone_transfers_fee_non_negative CHECK (fee_amount >= 0),
    CONSTRAINT spirit_stone_transfers_amount_equation CHECK (received_amount = gross_amount - fee_amount),
    CONSTRAINT spirit_stone_transfers_received_positive CHECK (received_amount > 0),
    CONSTRAINT spirit_stone_transfers_revision_not_blank CHECK (length(trim(policy_revision)) > 0),
    CONSTRAINT spirit_stone_transfers_status_valid CHECK (status = 'COMPLETED')
);

CREATE INDEX IF NOT EXISTS spirit_stone_transfers_sender_history
ON spirit_stone_transfers (sender_player_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS spirit_stone_transfers_recipient_history
ON spirit_stone_transfers (recipient_player_id, created_at DESC, id DESC);
