ALTER TABLE players
    ADD COLUMN IF NOT EXISTS character_reset_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_character_reset_at TIMESTAMPTZ;

ALTER TABLE players
    DROP CONSTRAINT IF EXISTS players_character_reset_count_non_negative,
    ADD CONSTRAINT players_character_reset_count_non_negative CHECK (character_reset_count >= 0);

CREATE TABLE IF NOT EXISTS player_character_reset_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id VARCHAR(50) NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    reset_number INTEGER NOT NULL,
    operation_id TEXT NOT NULL UNIQUE,
    policy_revision VARCHAR(100) NOT NULL,
    retained_spirit_stone NUMERIC(30, 0) NOT NULL,
    before_snapshot JSONB NOT NULL,
    reset_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_character_reset_number_positive CHECK (reset_number > 0),
    CONSTRAINT player_character_reset_stone_non_negative CHECK (retained_spirit_stone >= 0),
    CONSTRAINT player_character_reset_revision_not_blank CHECK (length(trim(policy_revision)) > 0),
    CONSTRAINT player_character_reset_player_number_unique UNIQUE (player_id, reset_number)
);

CREATE INDEX IF NOT EXISTS player_character_reset_history_latest
ON player_character_reset_history (player_id, reset_at DESC, id DESC);
